AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the necessary lambda functions for the Syntinel application.
Parameters:
  CoreCloudStackName:
    Type: String
    Default: syntinel-core
    Description: (Required) The name for the cloudformation stack used to create the IAM policies and roles.

  ResolverIamStackName:
    Type: String
    Default: syntinel-resolver-ec2utils-iam
    Description: (Required) The name for the cloudformation stack used to create the IAM policies and roles specific to this resolver.

  SetInstanceStateFunctionName:
    Type: String
    Default: syntinel-resolver-ec2-setstate
    Description: The name for the function that performs actions against EC2 instances.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "REQUIRED INPUT"
      Parameters:
      - CoreCloudStackName
      - ResolverIamStackName
    - Label:
        default: "ADVANCED CONFIGURATION: Core Lambda Function Names (Required)"
      Parameters:
      - SetInstanceStateFunctionName

Resources: 
  SyntinelResolverEc2UtilsSetInstanceState:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref SetInstanceStateFunctionName
      Description: Sets the state of an EC2 instance
      Role: { "Fn::ImportValue" : { "Fn::Sub" : "${ResolverIamStackName}-RoleArn" } }
      Code:
        S3Bucket: { "Fn::ImportValue" : { "Fn::Sub" : "${CoreCloudStackName}-S3BucketNameLambda" } }
        S3Key: { "Fn::ImportValue" : { "Fn::Sub" : "${CoreCloudStackName}-S3BucketObjectKeyLambda" } }
      Handler: Syntinel.Aws::Syntinel.Aws.LambdaFunctions::Ec2UtilsSetInstanceState
      Runtime: dotnetcore2.1
      Timeout: 30
      Environment:
        Variables:
          StatusUrl: !Join ["", [ { "Fn::ImportValue" : { "Fn::Sub" : "${CoreCloudStackName}-InvokeUrl" } }, "/status" ] ]

Outputs:
  StackName:
    Description: The name of this stack.
    Value:  !Ref AWS::StackName

