AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the initial RestApi for running the Syntinel application.

Parameters:
  ### Rest API
  RestApiName:
    Type: String
    Default: syntinel
    Description: (Required) The name for the REST Api.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "API Gateway (Required)"
      Parameters:
      - RestApiName

Resources:
  # Main Rest API
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref RestApiName
      Description: API Entry points for the Syntinel application.
      EndpointConfiguration:
        Types:
        - REGIONAL

  # Methods
  HelloWorldMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: { "Fn::GetAtt": ["RestApi", "RootResourceId"] }
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: "{'statusCode': 200}"
        IntegrationResponses:
        - StatusCode: 200
          ResponseTemplates:
            application/json: "{\"message\": \"Hello From Syntinel.\"}"
            text/html: Hello From Syntinel.
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: Empty

Outputs:
  Version:
    Description: Cloud Formation Template Version
    Value: 0.1.21144.0

  StackName:
    Description: The name of this stack.
    Value:  !Ref AWS::StackName

  ApiGateway:
    Description: The resource id for the API Gateway.
    Value: !Ref RestApi
    Export:
      Name: !Sub "${AWS::StackName}-SyntinelApiGateway"

  RootResourceId:
    Description: The root resource id for the API Gateway. 
    Value: !GetAtt
        - RestApi
        - RootResourceId
    Export:
      Name: !Sub "${AWS::StackName}-RootResourceId"
